Шахматисты и табличная верстка
fd1-44-17-group/kateandreeshcheva pull request #14
Opened 2017-09-26 16:46 UTC by KateAndreeshcheva

@fd1-44-17 
please review

2017-09-27 05:17 UTC, fd1-44-17 requested changes

2017-09-27 05:17 UTC, fd1-44-17 commented on dzz/maket_table/index.html
> +<!DOCTYPE html>
макет должен быть сделан на основе задания в library/рабочей тетради.

2017-09-27 05:17 UTC, fd1-44-17 commented on work/chess_media/assets/css/style.css
> +        float: left;
для чего float и absolute?

2017-09-27 05:17 UTC, fd1-44-17 commented on work/chess_media/index.html
> +    <a class="first">
нельзя в строчные элементы вставлять блочные

2017-10-01 11:56 UTC, KateAndreeshcheva commented
@fd1-44-17 
please review

2017-10-03 09:06 UTC, KateAndreeshcheva commented
@fd1-44-17
please review

2017-10-05 12:07 UTC, fd1-44-17 approved these changes

2017-10-05 12:08 UTC, merged