надеюсь это последний коммит первого дз и файлы никуда не пропадут
fd1-44-17-group/kateandreeshcheva pull request #3
Opened 2017-09-04 12:51 UTC by KateAndreeshcheva

@fd1-44-17 
:)

2017-09-04 16:25 UTC, KateAndreeshcheva commented
@fd1-44-17 please review

2017-09-07 06:10 UTC, fd1-44-17 requested changes
Почти хорошо.

2017-09-07 06:10 UTC, fd1-44-17 commented on dzz/1/student.html
> +    <p>В свое время драматург Михаил Львовский написал песню, которую студенчество по праву считает "своей", хотя написана она была не студентом и не о студентах. Это песня "Глобус". В ней есть слова
кавычки должны быть не "", а &lquot; &rquot;

2017-09-07 08:29 UTC, KateAndreeshcheva commented
@fd1-44-17
please review

2017-09-07 08:55 UTC, fd1-44-17 approved these changes
зачем только вы library добавили?)))

2017-09-07 08:55 UTC, merged

2017-09-07 09:04 UTC, KateAndreeshcheva commented
@fd1-44-17
Потому что на ветке мастер у меня Library была пустая) а теперь все файлы в сборе ) вы же сами сказали коммитить так, чтобы сделать pull и все файлы были на месте )) или я не так поняла?)